language: scala

scala:
  - 2.11.0

jdk:
  - oraclejdk8

script:
  - sbt spDist
  - sbt clean coverage test

after_success:
  - sbt coverageReport coverageAggregate coveralls

env:
  global:
    - secure: "n4GFhAGE8qmB6jJoiqUlsgvPAoNaXp7a6CxoAMROWtg0N9oFAZraWXjEdnGvofN7/i0jlk7C1vVPiX4jUGmyP7d5B4qh2gB9aPtuHWUoIwNST3Tk3Hnv4Kkmqctbcc2zaeXHeWPQHvELP0UDLyPWlSTejp+dDy1vKHHoqLJTtlCvufCWen9bPbMcWpnFGxhoKTPPdzpn0ocOT0HMUNl+ILDATe8tCbFx/ob5+XXg+toktl8xYuZ1ZM1HJDrRilyUCgoIvqsS5Tf8G3bBjRV+lp53Tusx/a5ysf0BlqjZYy0Hg2YC18VRMLysEWnqRqwN0TlFeydZjzFRLB8OJn5fjNj6Qmvd435rV/2Q8ytnetu4kdwUHbAflieMNHIWZwv6TnbzYlzarNgxhGizR0P8Li/wr3pjmDuBxJqs2ktLSRh8352YP8hraDyup3RE98mgI14EbVFWdGti03ZgzRB5uhG0Gi6oo4KuhuSGCxqVHCNrbuDuqECuvH5V3gGw/XZ8F6LymozCWTcM6LsdstUd3x6uvqjPJFbMe2GfqqfV0iFEuV+t3KaH2jw0ngRV4vhmL10pyoVcl2cWbJJn6j/tC3ZLvxVLpmbtyvnJHjI+r40aKZwLsTNs6JVo/IoiPg+t6UNqAPVytIhPCK4JLbzGQWkSxZpoK2HsyKMKf6eEiTA="